version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama-init
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./ISO:/app/ISO
      - ./faiss_index:/app/faiss_index
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    volumes:
      - ./init-ollama.sh:/init-ollama.sh
    entrypoint: ["/bin/sh", "/init-ollama.sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: